version: 2.1
executors:
  golang-executor:
    environment:
      - DEP_VERSION: 0.5.1
      - ORG_NAME: nmaupu
      - PROJECT_NAME: vault-secret
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/nmaupu/vault-secret

jobs:
  prepare:
    executor: golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ .Revision }}-{{ checksum "Gopkg.lock" }}
            - vendor-{{ .Branch }}-{{ .Revision }}-
      - run:
          name: Installing dep tool
          command: |
            curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
            chmod +x $GOPATH/bin/dep
      - run:
          name: Golang dep installation
          command: |
            if [ ! -d $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME/vendor ]; then
              cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME && \
              make dep
            fi
      - save_cache:
          name: Saving cache for project vendor directory
          key: vendor-{{ .Branch }}-{{ .Revision }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Operator-sdk installation
          command: |
              mkdir -p $GOPATH/src/github.com/operator-framework
              cd $GOPATH/src/github.com/operator-framework
              git clone https://github.com/operator-framework/operator-sdk.git
              cd $GOPATH/src/github.com/operator-framework/operator-sdk
              git checkout master
              make tidy
              make install
      - persist_to_workspace:
          root: /go
          paths:
            - src/github.com/operator-framework/operator-sdk
            - bin/operator-sdk
  build:
    executor: golang-executor
    steps:
      - attach_workspace:
          at: /go
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ .Revision }}-{{ checksum "Gopkg.lock" }}
            - vendor-{{ .Branch }}-{{ .Revision }}-
      - restore_cache:
          keys:
            - release-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Building application
          command: |
            cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME
            make build
            make push
            make openapi
      - save_cache:
          name: Saving cache for binary
          key: build-{{ .Branch }}-{{ .Revision }}
          paths:
            - build/_output/bin/vault-secret
  prepare-release:
    executor: golang-executor
    steps:
      - checkout
      - run:
          name: Preparing for release
          command: |
            make CI-release-prepare
      - save_cache:
          name: Saving cache for release version
          key: release-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
          paths:
            - release
            - version/version.go
  release-github:
    executor: golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - release-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - restore_cache:
          keys:
            - build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Publish release on Github
          command: |
            go get github.com/tcnksm/ghr
            cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME
            make CI-process-release

workflows:
  version: 2.1
  branch:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
  release:
    jobs:
      - prepare:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - prepare-release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - build:
          requires:
            - prepare
            - prepare-release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - release-github:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
