version: 2.1
executors:
  golang-executor:
    environment:
      - ORG_NAME: nmaupu
      - PROJECT_NAME: vault-secret
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/nmaupu/vault-secret

# https://circleci.com/docs/2.0/reusing-config/
commands:
  cmd_prepare_release:
    description: "Prepare either a test or a milestone release"
    parameters:
      release_name:
        type: string
        default: "master"
    steps:
      - checkout
      - run:
          name: Preparing for release
          command: |
            RELEASE_NAME=<< parameters.release_name >> make CI-prepare-release
      - save_cache:
          name: Saving cache for release version
          key: release-{{ .Revision }}-<< parameters.release_name >>
          paths:
            - release
            - version/version.go
  cmd_docker_build_push:
    description: "Build and push docker image"
    parameters:
      image_name:
        type: string
        default: "test"
    steps:
      - attach_workspace:
          at: /go
      - checkout
      - restore_cache:
          keys:
            - release-{{ .Revision }}-<< parameters.image_name >>
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_LOGIN --password-stdin
      - run:
          name: Building docker image
          command: |
            cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME
            RELEASE_NAME="<< parameters.image_name >>" make CI-docker-build
      - run:
          name: Pushing docker image
          command: |
            cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME
            RELEASE_NAME="<< parameters.image_name >>" make CI-docker-push

jobs:
  docker-build-push-branch:
    executor: golang-executor
    steps:
      - cmd_docker_build_push:
          image_name: ${CIRCLE_BRANCH}
  docker-build-push-tag:
    executor: golang-executor
    steps:
      - cmd_docker_build_push:
          image_name: ${CIRCLE_TAG}
  prepare-release-branch:
    executor: golang-executor
    steps:
      - cmd_prepare_release:
          release_name: ${CIRCLE_BRANCH}
  prepare-release-tag:
    executor: golang-executor
    steps:
      - cmd_prepare_release:
          release_name: ${CIRCLE_TAG}
  release-github:
    executor: golang-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - release-{{ .Revision }}-{{ .Environment.CIRCLE_TAG }}
      - restore_cache:
          keys:
            - build-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Publish release on Github
          command: |
            go get github.com/tcnksm/ghr
            cd $GOPATH/src/github.com/$ORG_NAME/$PROJECT_NAME
            make CI-process-release

workflows:
  version: 2.1
  branch:
    jobs:
      - prepare-release-branch
      - docker-build-push-branch:
          requires:
            - prepare-release-branch
  release:
    jobs:
      - prepare-release-tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - docker-build-push-tag:
          requires:
            - prepare-release-tag
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - release-github:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
