apiVersion: maupu.org/v1beta1
kind: VaultSecret
metadata:
  name: example-vaultsecret
spec:
  secretName: vault-secret-test
  secrets:
    - secretKey: username
      kvPath: secrets/kv
      path: test
      field: username
    - secretKey: password
      kvPath: secrets/kv
      path: test
      field: password
  config:
    addr: https://vault.example.com
    # namespace: example-namespace
    auth:
      kubernetes:
        role: myrole
        cluster: kubernetes
#   auth:
#     token: ...
#   auth:
#     approle:
#       role_id: ...
#       secret_id: ...
