apiVersion: maupu.org/v1beta1
kind: VaultSecret
metadata:
  name: example-vaultsecret
  namespace: nma
spec:
  secretName: vault-secret-test
  secrets:
    - secretKey: username
      path: secret/test
      field: username
    - secretKey: password
      path: secret/test
      field: password
  config:
    addr: https://vault.example.com
    auth:
      kubernetes:
        role: myrole
        cluster: kubernetes
#   auth:
#     token: ...
#   auth:
#     approle:
#       role_id: ...
#       secret_id: ...
