apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: vaultsecrets.maupu.org
spec:
  group: maupu.org
  names:
    kind: VaultSecret
    listKind: VaultSecretList
    plural: vaultsecrets
    singular: vaultsecret
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                addr:
                  type: string
                auth:
                  properties:
                    approle:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    kubernetes:
                      properties:
                        cluster:
                          type: string
                        role:
                          type: string
                      required:
                      - role
                      - cluster
                      type: object
                  type: object
                insecure:
                  type: boolean
              required:
              - addr
              - auth
              type: object
            secretName:
              type: string
            secrets:
              items:
                properties:
                  field:
                    type: string
                  path:
                    type: string
                  secretKey:
                    type: string
                required:
                - secretKey
                - path
                - field
                type: object
              type: array
            targetNamespace:
              type: string
          required:
          - config
          - secrets
          type: object
        status:
          properties:
            configured:
              type: boolean
            upToDate:
              type: boolean
          required:
          - configured
          - upToDate
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
