apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: vault-secret-role
  namespace: nma
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - replicasets
  - deployments
  verbs: ["get", "watch", "list"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - maupu.org
  resources:
  - vaultsecrets
  verbs: ["get", "watch", "list", "update", "patch"]

