kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-secret
  namespace: nma
subjects:
- kind: ServiceAccount
  name: default
  namespace: nma
roleRef:
  kind: Role
  name: vault-secret-role
  apiGroup: rbac.authorization.k8s.io
